### ISSUE TITLE
Cannot customize menu actionbar item for specific fragment

### ISSUE THREAD

**Issue by aemxn** [danilao/fragments-viewpager-example#1]
Hey, I just stumbled upon this example that I might wanna use in my project.

I've tried it but I can't seem to have customizable actionbar item for each fragment that I want. For example, in Tab 1, I want Item A, in Tab 2, Item A needs to be hidden and Item B is shown. However, this is not the case. All of the items are shown when I slide to each tabs.

I've used `setHasOptionsMenu(true)` to each fragments but fails. Also, `onPrepareOptionsMenu` cannot be done. I hope for a fix or hack here.

Thanks for the trick though.

**Edit:** I'm using this in a ViewPager tabs.
**Edit 2:** tl;dr And I need to use the actionbar menu item for each fragment.

**Comment by ppamorim** [comment]
Man, create a interface for do it, it very very very simple:

public static interface ControlActivity {
        void doThis(Param param);
}

**Comment by kevinstyle** [comment]
Hi, ppamorim
could u describe more detail about how to do using Interface ? I had the same problem too.

**Comment by ppamorim** [comment]
Now you can use SmartTabLayout instead this deprecated library.

**Comment by kevinstyle** [comment]
Hi, ppamorim
do u mean https://github.com/ogaclejapan/SmartTabLayout ?

**Comment by ppamorim** [comment]
Yes
